
" mouse stuff
set mouse=a
set clipboard=unnamed,unnamedplus

" tab stuff
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" look & feel
syntax on
set timeoutlen=50 ttimeoutlen=0
set background=dark
set number
set relativenumber
set showmatch
set autoindent smartindent
set showmode
set listchars=tab:▸\ ,trail:·
set list
set shortmess=I

set incsearch
set ignorecase
set smartcase
set hlsearch

" statusline
set laststatus=2
set noshowmode

colorscheme darcula

" vim-plug
call plug#begin('~/.vim/vim-plugs')
Plug 'junegunn/goyo.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'edkolev/tmuxline.vim'
call plug#end()

let g:airline_theme='distinguished'
let g:airline_powerline_fonts = 1
map <c-t> :FZF!<cr>

set tags+=.git/tags

command! Hi80 highlight OverLength ctermbg=red ctermfg=white guibg=#592929 | match OverLength /\%81v.\+/

fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

if has('autocmd')
  "autocmd FileType c,cpp,java,python,lua,xml,ftl,quakec,vim )

  filetype plugin indent on
  au BufNewFile,BufRead *.ftl set filetype=html
  au BufNewFile,BufRead *.xml set filetype=xml
  au BufNewFile,BufRead *.py Hi80
  au BufNewFile,BufRead *.qc set filetype=quakec

  autocmd BufWritePost *
    \ if filereadable('tags') |
    \   call system('ctags -a '.expand('%')) |
    \ endif
endif

" mappings
noremap K :tabnext<CR>
nnoremap J :tabprevious<CR>

set pastetoggle=<F2>
"nnoremap <F2> :set invpaste paste?<CR>

map <Esc>s :w<CR>
imap <Esc>s  <C-O>:w<CR>

nmap ZA :qall!<CR>

" more readline-like kill word
inoremap <C-w> <C-\><C-o>dB
inoremap <C-BS> <C-\><C-o>db

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

syntax match csvHeading /\%1l\%(\%("\zs\%([^"]\|""\)*\ze"\)\|\%(\zs[^,"]*\ze\)\)/
highlight def link csvHeading Type

" Sort words on line
command -nargs=0 -range SortLine <line1>,<line2>call setline('.',join(sort(split(getline('.'),' ')),' '))
